name: Zenodo Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Run Zenodo Deploy
      uses: nmfs-opensci/zenodo-ga@main
      with:
        token: ${{ secrets.ZENODO_TOKEN }}
        zenodo_json: .zenodo.json   # either a .zenodo.json file or CITATION.cff
        doi: 10.5281/zenodo.10811321
